// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Public account fields (never includes password hash).
 */
export type AccountResponse = {
    email?: string | null;
    id: string;
    is_bot: boolean;
    is_instance_admin: boolean;
};

/**
 * Add a community member to a space (restricted / manual).
 */
export type AddSpaceMemberRequest = {
    account_id: string;
};

/**
 * Assign a role to a member.
 */
export type AssignRoleRequest = {
    role_id: string;
};

/**
 * Cursor page of audit events (newest first).
 */
export type AuditEventListResponse = {
    has_more: boolean;
    items: Array<AuditEventResponse>;
};

/**
 * One audit log entry.
 */
export type AuditEventResponse = {
    action: string;
    actor_account_id?: string | null;
    community_id: string;
    created_at: string;
    id: string;
    metadata: {
        [key: string]: unknown;
    };
    space_id?: string | null;
    summary: string;
    target_id?: string | null;
    target_type?: string | null;
};

/**
 * Authenticated session payload.
 */
export type AuthSessionResponse = {
    account: AccountResponse;
};

/**
 * Bulk assign roles to a group (or ungroup when `group_id` is null).
 */
export type BulkAssignRoleGroupRequest = {
    group_id?: string | null;
    role_ids: Array<string>;
};

/**
 * Categories in a community scope.
 */
export type CategoryListResponse = {
    categories: Array<CategoryResponse>;
};

/**
 * Public category representation.
 */
export type CategoryResponse = {
    community_id: string;
    created_at: string;
    id: string;
    name: string;
    position: number;
    space_id?: string | null;
    updated_at: string;
};

/**
 * Change email (requires current password; applied immediately until F117 adds confirmation mail).
 */
export type ChangeEmailRequest = {
    current_password: string;
    email: string;
};

/**
 * Change password (requires current password).
 */
export type ChangePasswordRequest = {
    current_password: string;
    new_password: string;
    /**
     * When true, delete all other sessions for this account (current session stays).
     */
    revoke_other_sessions?: boolean | null;
};

/**
 * Channels in a list scope.
 */
export type ChannelListResponse = {
    channels: Array<ChannelResponse>;
};

/**
 * Public channel representation.
 */
export type ChannelResponse = {
    archived_at?: string | null;
    category_id?: string | null;
    community_id: string;
    config: unknown;
    created_at: string;
    id: string;
    name: string;
    position: number;
    space_id?: string | null;
    topic: string;
    type: ChannelType;
    updated_at: string;
};

/**
 * Channel type registry (F027). Typed features attach in later milestones.
 */
export type ChannelType = 'text' | 'voice' | 'forum' | 'announcement' | 'calendar' | 'scheduling' | 'docs' | 'tasks' | 'media' | 'stage' | 'streaming';

/**
 * Who may create communities on this instance.
 */
export type CommunityCreationMode = 'open' | 'admin_only' | 'single';

/**
 * List wrapper for communities the caller belongs to.
 */
export type CommunityListResponse = {
    communities: Array<CommunityResponse>;
};

/**
 * Cursor page of community members.
 */
export type CommunityMemberListResponse = {
    has_more: boolean;
    items: Array<CommunityMemberResponse>;
};

/**
 * One community member with profile display fields.
 */
export type CommunityMemberResponse = {
    account_id: string;
    avatar_url?: string | null;
    community_id: string;
    display_name: string;
    has_avatar: boolean;
    joined_at: string;
    nickname: string;
    role: CommunityMemberRole;
};

/**
 * Membership role within a community.
 */
export type CommunityMemberRole = 'owner' | 'member';

/**
 * Public community representation.
 */
export type CommunityResponse = {
    banner_url?: string | null;
    created_at: string;
    description: string;
    discoverable_on_instance: boolean;
    icon_url?: string | null;
    id: string;
    invite_path?: string | null;
    invite_splash_url?: string | null;
    join_mode: JoinMode;
    name: string;
    owner_account_id: string;
    slug: string;
    tag_badge_url?: string | null;
    tag_color: string;
    tag_name: string;
    timezone: string;
    updated_at: string;
};

/**
 * Create a category in a community (optionally scoped to a Space).
 */
export type CreateCategoryRequest = {
    name: string;
    space_id?: string | null;
};

/**
 * Create a channel in a community scope.
 */
export type CreateChannelRequest = {
    category_id?: string | null;
    config?: unknown;
    name: string;
    space_id?: string | null;
    topic?: string | null;
    type: ChannelType;
};

/**
 * Create a community.
 */
export type CreateCommunityRequest = {
    description?: string | null;
    discoverable_on_instance?: boolean | null;
    join_mode?: null | JoinMode;
    name: string;
    slug?: string | null;
    timezone?: string | null;
};

/**
 * Create a community invite.
 */
export type CreateInviteRequest = {
    expire_after?: null | InviteExpireAfter;
    /**
     * `null` / omitted = unlimited. Otherwise `1..=1000`.
     */
    max_uses?: number | null;
};

/**
 * Create a role group.
 */
export type CreateRoleGroupRequest = {
    name: string;
};

/**
 * Create a custom role.
 */
export type CreateRoleRequest = {
    color?: string | null;
    gradient?: string | null;
    group_id?: string | null;
    hoist?: boolean | null;
    icon_emoji?: string | null;
    manage_roles?: boolean | null;
    mentionable?: boolean | null;
    name: string;
    permissions?: unknown;
    role_card?: unknown;
    short_tag?: string | null;
    weight?: number | null;
};

/**
 * Create a Space in a community.
 */
export type CreateSpaceRequest = {
    description?: string | null;
    game?: string | null;
    name: string;
    topic?: string | null;
    visibility?: null | SpaceVisibility;
};

/**
 * Confirm community deletion by typing the community name (F025).
 */
export type DeleteCommunityRequest = {
    confirm_name: string;
};

/**
 * JSON error envelope for `/api/v1` and unknown routes.
 */
export type ErrorBody = {
    code: string;
    details?: {
        [key: string]: unknown;
    } | null;
    message: string;
    request_id: string;
};

/**
 * Explain why an actor has or lacks a permission.
 */
export type ExplainPermissionRequest = {
    account_id: string;
    channel_id?: string | null;
    community_id: string;
    permission: string;
};

/**
 * Permission explain result.
 */
export type ExplainPermissionResponse = {
    account_id: string;
    allowed: boolean;
    channel_id?: string | null;
    permission: string;
    steps: Array<PermissionExplainStep>;
};

/**
 * Instance settings visible to instance admins.
 */
export type InstanceSettingsResponse = {
    community_creation_mode: CommunityCreationMode;
    /**
     * When true, [`UpdateInstanceSettingsRequest::community_creation_mode`] is ignored.
     */
    community_creation_mode_locked: boolean;
    id: string;
    name: string;
    oidc_client_id?: string | null;
    oidc_enabled: boolean;
    oidc_issuer?: string | null;
    public_url: string;
    registration_mode: RegistrationMode;
    updated_at: string;
};

/**
 * Relative invite lifetime chosen before code generation.
 */
export type InviteExpireAfter = {
    unit: InviteExpireUnit;
    value: number;
};

/**
 * Units for [`InviteExpireAfter`].
 */
export type InviteExpireUnit = 'hours' | 'days' | 'months';

/**
 * List of invites for a community.
 */
export type InviteListResponse = {
    invites: Array<InviteResponse>;
};

/**
 * Preview for join-by-code UI (no sensitive creator detail beyond community).
 */
export type InvitePreviewResponse = {
    code: string;
    community_id: string;
    community_name: string;
    community_slug: string;
    exhausted: boolean;
    expired: boolean;
    paused: boolean;
};

/**
 * Public invite representation.
 */
export type InviteResponse = {
    code: string;
    community_id: string;
    created_at: string;
    created_by: string;
    expires_at?: string | null;
    id: string;
    max_uses?: number | null;
    paused: boolean;
    revoked_at?: string | null;
    uses: number;
};

/**
 * How accounts may join a community (invites/applications expand in later features).
 */
export type JoinMode = 'open' | 'invite' | 'application';

/**
 * Query filters for community audit log listing.
 */
export type ListAuditEventsQuery = {
    action?: string | null;
    actor_account_id?: string | null;
    after?: string | null;
    before?: string | null;
    limit?: number | null;
    space_id?: string | null;
};

/**
 * List categories query (`space_id` omitted = community-level).
 */
export type ListCategoriesQuery = {
    space_id?: string | null;
};

/**
 * List channels query.
 */
export type ListChannelsQuery = {
    category_id?: string | null;
    include_archived?: boolean | null;
    space_id?: string | null;
};

/**
 * Login with email and password.
 */
export type LoginRequest = {
    email: string;
    password: string;
};

/**
 * Build, version, and public instance policy flags for the SPA.
 */
export type MetaResponse = {
    community_creation_mode: CommunityCreationMode;
    name: string;
    /**
     * Whether SSO sign-in is configured and enabled for this instance.
     */
    oidc_enabled: boolean;
    /**
     * Whether email/password login and registration are offered.
     */
    password_login_enabled: boolean;
    registration_mode: RegistrationMode;
    version: string;
};

/**
 * One step in an explanation chain.
 */
export type PermissionExplainStep = {
    detail: string;
    outcome: string;
    stage: string;
};

/**
 * Overrides for a channel (includes category-scoped rows when applicable).
 */
export type PermissionOverrideListResponse = {
    overrides: Array<PermissionOverrideResponse>;
};

/**
 * Stored permission override.
 */
export type PermissionOverrideResponse = {
    account_id?: string | null;
    category_id?: string | null;
    channel_id?: string | null;
    community_id: string;
    created_at: string;
    id: string;
    permissions: unknown;
    role_id?: string | null;
    updated_at: string;
};

/**
 * Instance-wide presence snapshot (F018).
 */
export type PresenceEntry = {
    account_id: string;
    custom_status: string;
    status: PublicPresenceStatus;
};

/**
 * Online users visible on this instance.
 */
export type PresenceListResponse = {
    presences: Array<PresenceEntry>;
};

/**
 * Stored preference and gateway-reported status while connected.
 */
export type PresenceStatus = 'online' | 'idle' | 'dnd' | 'invisible';

/**
 * Public profile fields.
 */
export type ProfileResponse = {
    account_id: string;
    avatar_url?: string | null;
    banner_url?: string | null;
    bio: string;
    custom_status: string;
    display_name: string;
    has_avatar: boolean;
    has_banner: boolean;
    presence_status: PublicPresenceStatus;
};

/**
 * Presence exposed to clients (offline when disconnected or hidden from viewers).
 */
export type PublicPresenceStatus = 'online' | 'idle' | 'dnd' | 'invisible' | 'offline';

/**
 * Register with email, password, and display name.
 */
export type RegisterRequest = {
    display_name: string;
    email: string;
    password: string;
};

/**
 * Who may register new local accounts on this instance.
 */
export type RegistrationMode = 'open' | 'invite' | 'closed';

/**
 * Reorder categories by sending new positions in order.
 */
export type ReorderCategoriesRequest = {
    category_ids: Array<string>;
};

/**
 * Reorder channels in a scope by id list.
 */
export type ReorderChannelsRequest = {
    channel_ids: Array<string>;
};

/**
 * Reorder roles by id list (display `position` only; does not change weight).
 */
export type ReorderRolesRequest = {
    role_ids: Array<string>;
};

/**
 * List of role groups.
 */
export type RoleGroupListResponse = {
    groups: Array<RoleGroupResponse>;
};

/**
 * Role group (organizational).
 */
export type RoleGroupResponse = {
    community_id: string;
    created_at: string;
    display_order: number;
    id: string;
    name: string;
    updated_at: string;
};

/**
 * Roles in a community.
 */
export type RoleListResponse = {
    roles: Array<RoleResponse>;
};

/**
 * Public role representation.
 */
export type RoleResponse = {
    color: string;
    community_id: string;
    created_at: string;
    gradient?: string | null;
    group_id?: string | null;
    hoist: boolean;
    icon_emoji?: string | null;
    icon_object_key?: string | null;
    id: string;
    is_everyone: boolean;
    mentionable: boolean;
    name: string;
    permissions: unknown;
    /**
     * Display order only (drag-reorder).
     */
    position: number;
    role_card: unknown;
    short_tag: string;
    updated_at: string;
    /**
     * Unique 1–1000; lower = higher priority.
     */
    weight: number;
};

/**
 * Spaces in a community, ordered by position.
 */
export type SpaceListResponse = {
    spaces: Array<SpaceResponse>;
};

/**
 * Space members list.
 */
export type SpaceMemberListResponse = {
    members: Array<SpaceMemberResponse>;
};

/**
 * One space member with profile display fields.
 */
export type SpaceMemberResponse = {
    account_id: string;
    avatar_url?: string | null;
    display_name: string;
    has_avatar: boolean;
    joined_at: string;
    space_id: string;
};

/**
 * Public Space representation.
 */
export type SpaceResponse = {
    community_id: string;
    created_at: string;
    description: string;
    game: string;
    icon_url?: string | null;
    id: string;
    /**
     * Whether the caller is a member of this space.
     */
    is_member: boolean;
    name: string;
    position: number;
    topic: string;
    updated_at: string;
    visibility: SpaceVisibility;
};

/**
 * Who can see / enter a Space (F023 membership expands access rules).
 */
export type SpaceVisibility = 'open' | 'restricted';

/**
 * Transfer community ownership to another member (F025).
 */
export type TransferCommunityRequest = {
    account_id: string;
};

/**
 * Update a category (name, position, or scope).
 */
export type UpdateCategoryRequest = {
    name?: string | null;
    position?: number | null;
    space_id?: string | null;
};

/**
 * Update a channel.
 */
export type UpdateChannelRequest = {
    category_id?: string | null;
    config?: unknown;
    name?: string | null;
    position?: number | null;
    space_id?: string | null;
    topic?: string | null;
};

/**
 * Update community settings (owner).
 */
export type UpdateCommunityRequest = {
    description?: string | null;
    discoverable_on_instance?: boolean | null;
    invite_path?: string | null;
    join_mode?: null | JoinMode;
    name?: string | null;
    tag_color?: string | null;
    tag_name?: string | null;
    timezone?: string | null;
};

/**
 * Partial update of instance settings (instance admin only).
 */
export type UpdateInstanceSettingsRequest = {
    community_creation_mode?: null | CommunityCreationMode;
    name?: string | null;
    oidc_client_id?: string | null;
    oidc_enabled?: boolean | null;
    oidc_issuer?: string | null;
    public_url?: string | null;
    registration_mode?: null | RegistrationMode;
};

/**
 * Pause / unpause an invite.
 */
export type UpdateInviteRequest = {
    paused?: boolean | null;
};

/**
 * Update the caller's nickname in a community.
 */
export type UpdateNicknameRequest = {
    nickname: string;
};

/**
 * Patch display name, bio, presence, and/or custom status.
 */
export type UpdateProfileRequest = {
    bio?: string | null;
    custom_status?: string | null;
    /**
     * Empty string is allowed (new accounts start blank until set).
     */
    display_name?: string | null;
    presence_status?: null | PresenceStatus;
};

/**
 * Update a role group.
 */
export type UpdateRoleGroupRequest = {
    display_order?: number | null;
    name?: string | null;
};

/**
 * Update a role.
 */
export type UpdateRoleRequest = {
    clear_gradient?: boolean | null;
    /**
     * When true, remove the role from its group.
     */
    clear_group?: boolean | null;
    /**
     * Set true to clear icon emoji.
     */
    clear_icon_emoji?: boolean | null;
    color?: string | null;
    gradient?: string | null;
    group_id?: string | null;
    hoist?: boolean | null;
    icon_emoji?: string | null;
    manage_roles?: boolean | null;
    mentionable?: boolean | null;
    name?: string | null;
    permissions?: unknown;
    position?: number | null;
    role_card?: unknown;
    short_tag?: string | null;
    weight?: number | null;
};

/**
 * Update Space settings.
 */
export type UpdateSpaceRequest = {
    description?: string | null;
    game?: string | null;
    name?: string | null;
    position?: number | null;
    topic?: string | null;
    visibility?: null | SpaceVisibility;
};

/**
 * Upsert a role or member override on a channel.
 */
export type UpsertPermissionOverrideRequest = {
    permissions: unknown;
};

/**
 * Request a simulated channel list for an admin preview.
 */
export type ViewAsChannelsRequest = {
    /**
     * Required when `mode` is `member`.
     */
    account_id?: string | null;
    community_id: string;
    mode: ViewAsMode;
    /**
     * Extra role ids when `mode` is `roles` (`@everyone` is always included).
     */
    role_ids?: Array<string>;
    /**
     * Limit simulation to one Space (recommended for the sidebar).
     */
    space_id?: string | null;
};

/**
 * Simulated channel visibility for View As (read-only; does not change the session).
 */
export type ViewAsChannelsResponse = {
    channels: Array<ChannelResponse>;
    /**
     * Short label for the toolbar (e.g. member display name or role names).
     */
    label: string;
    mode: ViewAsMode;
};

/**
 * How to build the synthetic actor for View As.
 */
export type ViewAsMode = 'member' | 'roles' | 'visitor';

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginErrors = {
    /**
     * Validation error
     */
    400: ErrorBody;
    /**
     * Invalid credentials
     */
    401: ErrorBody;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Logged in
     */
    200: AuthSessionResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutResponses = {
    /**
     * Logged out
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type GetMeErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * Current account
     */
    200: AuthSessionResponse;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type ChangeMyEmailData = {
    body: ChangeEmailRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me/email';
};

export type ChangeMyEmailErrors = {
    /**
     * Validation error
     */
    400: ErrorBody;
    /**
     * Wrong current password or not authenticated
     */
    401: ErrorBody;
    /**
     * Email taken
     */
    409: ErrorBody;
};

export type ChangeMyEmailError = ChangeMyEmailErrors[keyof ChangeMyEmailErrors];

export type ChangeMyEmailResponses = {
    /**
     * Email updated
     */
    200: AuthSessionResponse;
};

export type ChangeMyEmailResponse = ChangeMyEmailResponses[keyof ChangeMyEmailResponses];

export type ChangeMyPasswordData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me/password';
};

export type ChangeMyPasswordErrors = {
    /**
     * Validation error
     */
    400: ErrorBody;
    /**
     * Wrong current password or not authenticated
     */
    401: ErrorBody;
};

export type ChangeMyPasswordError = ChangeMyPasswordErrors[keyof ChangeMyPasswordErrors];

export type ChangeMyPasswordResponses = {
    /**
     * Password updated
     */
    204: void;
};

export type ChangeMyPasswordResponse = ChangeMyPasswordResponses[keyof ChangeMyPasswordResponses];

export type OidcCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/oidc/callback';
};

export type OidcCallbackErrors = {
    /**
     * Invalid callback
     */
    400: ErrorBody;
    /**
     * OIDC not configured
     */
    404: ErrorBody;
};

export type OidcCallbackError = OidcCallbackErrors[keyof OidcCallbackErrors];

export type OidcCallbackResponses = {
    /**
     * HTML bounce to SPA with session cookie
     */
    200: unknown;
};

export type StartOidcLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/oidc/start';
};

export type StartOidcLoginErrors = {
    /**
     * OIDC not configured
     */
    404: ErrorBody;
    /**
     * Internal error
     */
    500: ErrorBody;
};

export type StartOidcLoginError = StartOidcLoginErrors[keyof StartOidcLoginErrors];

export type StartOidcLoginResponses = {
    /**
     * HTML bounce to OIDC provider
     */
    200: unknown;
};

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterErrors = {
    /**
     * Validation error
     */
    400: ErrorBody;
    /**
     * Registration closed or CSRF
     */
    403: ErrorBody;
    /**
     * Email taken
     */
    409: ErrorBody;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Account created
     */
    201: AuthSessionResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type DeleteCategoryData = {
    body?: never;
    path: {
        /**
         * Category id
         */
        category_id: string;
    };
    query?: never;
    url: '/api/v1/categories/{category_id}';
};

export type DeleteCategoryErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type DeleteCategoryError = DeleteCategoryErrors[keyof DeleteCategoryErrors];

export type DeleteCategoryResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteCategoryResponse = DeleteCategoryResponses[keyof DeleteCategoryResponses];

export type GetCategoryData = {
    body?: never;
    path: {
        /**
         * Category id
         */
        category_id: string;
    };
    query?: never;
    url: '/api/v1/categories/{category_id}';
};

export type GetCategoryErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not a member
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type GetCategoryError = GetCategoryErrors[keyof GetCategoryErrors];

export type GetCategoryResponses = {
    /**
     * Category
     */
    200: CategoryResponse;
};

export type GetCategoryResponse = GetCategoryResponses[keyof GetCategoryResponses];

export type UpdateCategoryData = {
    body: UpdateCategoryRequest;
    path: {
        /**
         * Category id
         */
        category_id: string;
    };
    query?: never;
    url: '/api/v1/categories/{category_id}';
};

export type UpdateCategoryErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type UpdateCategoryError = UpdateCategoryErrors[keyof UpdateCategoryErrors];

export type UpdateCategoryResponses = {
    /**
     * Updated category
     */
    200: CategoryResponse;
};

export type UpdateCategoryResponse = UpdateCategoryResponses[keyof UpdateCategoryResponses];

export type ListCategoryPermissionOverridesData = {
    body?: never;
    path: {
        /**
         * Category id
         */
        category_id: string;
    };
    query?: never;
    url: '/api/v1/categories/{category_id}/permission-overrides';
};

export type ListCategoryPermissionOverridesErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type ListCategoryPermissionOverridesError = ListCategoryPermissionOverridesErrors[keyof ListCategoryPermissionOverridesErrors];

export type ListCategoryPermissionOverridesResponses = {
    /**
     * Override list
     */
    200: PermissionOverrideListResponse;
};

export type ListCategoryPermissionOverridesResponse = ListCategoryPermissionOverridesResponses[keyof ListCategoryPermissionOverridesResponses];

export type UpsertCategoryMemberPermissionOverrideData = {
    body: UpsertPermissionOverrideRequest;
    path: {
        /**
         * Category id
         */
        category_id: string;
        /**
         * Member account id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/categories/{category_id}/permission-overrides/members/{account_id}';
};

export type UpsertCategoryMemberPermissionOverrideErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type UpsertCategoryMemberPermissionOverrideError = UpsertCategoryMemberPermissionOverrideErrors[keyof UpsertCategoryMemberPermissionOverrideErrors];

export type UpsertCategoryMemberPermissionOverrideResponses = {
    /**
     * Override saved
     */
    200: PermissionOverrideResponse;
};

export type UpsertCategoryMemberPermissionOverrideResponse = UpsertCategoryMemberPermissionOverrideResponses[keyof UpsertCategoryMemberPermissionOverrideResponses];

export type UpsertCategoryRolePermissionOverrideData = {
    body: UpsertPermissionOverrideRequest;
    path: {
        /**
         * Category id
         */
        category_id: string;
        /**
         * Role id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/categories/{category_id}/permission-overrides/roles/{role_id}';
};

export type UpsertCategoryRolePermissionOverrideErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type UpsertCategoryRolePermissionOverrideError = UpsertCategoryRolePermissionOverrideErrors[keyof UpsertCategoryRolePermissionOverrideErrors];

export type UpsertCategoryRolePermissionOverrideResponses = {
    /**
     * Override saved
     */
    200: PermissionOverrideResponse;
};

export type UpsertCategoryRolePermissionOverrideResponse = UpsertCategoryRolePermissionOverrideResponses[keyof UpsertCategoryRolePermissionOverrideResponses];

export type DeleteChannelData = {
    body?: never;
    path: {
        /**
         * Channel id
         */
        channel_id: string;
    };
    query?: never;
    url: '/api/v1/channels/{channel_id}';
};

export type DeleteChannelErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type DeleteChannelError = DeleteChannelErrors[keyof DeleteChannelErrors];

export type DeleteChannelResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteChannelResponse = DeleteChannelResponses[keyof DeleteChannelResponses];

export type GetChannelData = {
    body?: never;
    path: {
        /**
         * Channel id
         */
        channel_id: string;
    };
    query?: never;
    url: '/api/v1/channels/{channel_id}';
};

export type GetChannelErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not a member
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type GetChannelError = GetChannelErrors[keyof GetChannelErrors];

export type GetChannelResponses = {
    /**
     * Channel
     */
    200: ChannelResponse;
};

export type GetChannelResponse = GetChannelResponses[keyof GetChannelResponses];

export type UpdateChannelData = {
    body: UpdateChannelRequest;
    path: {
        /**
         * Channel id
         */
        channel_id: string;
    };
    query?: never;
    url: '/api/v1/channels/{channel_id}';
};

export type UpdateChannelErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type UpdateChannelError = UpdateChannelErrors[keyof UpdateChannelErrors];

export type UpdateChannelResponses = {
    /**
     * Updated channel
     */
    200: ChannelResponse;
};

export type UpdateChannelResponse = UpdateChannelResponses[keyof UpdateChannelResponses];

export type ArchiveChannelData = {
    body?: never;
    path: {
        /**
         * Channel id
         */
        channel_id: string;
    };
    query?: never;
    url: '/api/v1/channels/{channel_id}/archive';
};

export type ArchiveChannelErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type ArchiveChannelError = ArchiveChannelErrors[keyof ArchiveChannelErrors];

export type ArchiveChannelResponses = {
    /**
     * Archived channel
     */
    200: ChannelResponse;
};

export type ArchiveChannelResponse = ArchiveChannelResponses[keyof ArchiveChannelResponses];

export type CloneChannelData = {
    body?: never;
    path: {
        /**
         * Channel id
         */
        channel_id: string;
    };
    query?: never;
    url: '/api/v1/channels/{channel_id}/clone';
};

export type CloneChannelErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type CloneChannelError = CloneChannelErrors[keyof CloneChannelErrors];

export type CloneChannelResponses = {
    /**
     * Cloned channel
     */
    201: ChannelResponse;
};

export type CloneChannelResponse = CloneChannelResponses[keyof CloneChannelResponses];

export type ListChannelPermissionOverridesData = {
    body?: never;
    path: {
        /**
         * Channel id
         */
        channel_id: string;
    };
    query?: never;
    url: '/api/v1/channels/{channel_id}/permission-overrides';
};

export type ListChannelPermissionOverridesErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type ListChannelPermissionOverridesError = ListChannelPermissionOverridesErrors[keyof ListChannelPermissionOverridesErrors];

export type ListChannelPermissionOverridesResponses = {
    /**
     * Override list
     */
    200: PermissionOverrideListResponse;
};

export type ListChannelPermissionOverridesResponse = ListChannelPermissionOverridesResponses[keyof ListChannelPermissionOverridesResponses];

export type UpsertChannelMemberPermissionOverrideData = {
    body: UpsertPermissionOverrideRequest;
    path: {
        /**
         * Channel id
         */
        channel_id: string;
        /**
         * Member account id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/channels/{channel_id}/permission-overrides/members/{account_id}';
};

export type UpsertChannelMemberPermissionOverrideErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type UpsertChannelMemberPermissionOverrideError = UpsertChannelMemberPermissionOverrideErrors[keyof UpsertChannelMemberPermissionOverrideErrors];

export type UpsertChannelMemberPermissionOverrideResponses = {
    /**
     * Override saved
     */
    200: PermissionOverrideResponse;
};

export type UpsertChannelMemberPermissionOverrideResponse = UpsertChannelMemberPermissionOverrideResponses[keyof UpsertChannelMemberPermissionOverrideResponses];

export type UpsertChannelRolePermissionOverrideData = {
    body: UpsertPermissionOverrideRequest;
    path: {
        /**
         * Channel id
         */
        channel_id: string;
        /**
         * Role id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/channels/{channel_id}/permission-overrides/roles/{role_id}';
};

export type UpsertChannelRolePermissionOverrideErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type UpsertChannelRolePermissionOverrideError = UpsertChannelRolePermissionOverrideErrors[keyof UpsertChannelRolePermissionOverrideErrors];

export type UpsertChannelRolePermissionOverrideResponses = {
    /**
     * Override saved
     */
    200: PermissionOverrideResponse;
};

export type UpsertChannelRolePermissionOverrideResponse = UpsertChannelRolePermissionOverrideResponses[keyof UpsertChannelRolePermissionOverrideResponses];

export type RestoreChannelData = {
    body?: never;
    path: {
        /**
         * Channel id
         */
        channel_id: string;
    };
    query?: never;
    url: '/api/v1/channels/{channel_id}/restore';
};

export type RestoreChannelErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type RestoreChannelError = RestoreChannelErrors[keyof RestoreChannelErrors];

export type RestoreChannelResponses = {
    /**
     * Restored channel
     */
    200: ChannelResponse;
};

export type RestoreChannelResponse = RestoreChannelResponses[keyof RestoreChannelResponses];

export type ListCommunitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/communities';
};

export type ListCommunitiesErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
};

export type ListCommunitiesError = ListCommunitiesErrors[keyof ListCommunitiesErrors];

export type ListCommunitiesResponses = {
    /**
     * Membership communities
     */
    200: CommunityListResponse;
};

export type ListCommunitiesResponse = ListCommunitiesResponses[keyof ListCommunitiesResponses];

export type CreateCommunityData = {
    body: CreateCommunityRequest;
    path?: never;
    query?: never;
    url: '/api/v1/communities';
};

export type CreateCommunityErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Creation disallowed by instance policy
     */
    403: ErrorBody;
    /**
     * Slug conflict
     */
    409: ErrorBody;
    /**
     * Validation error
     */
    422: ErrorBody;
};

export type CreateCommunityError = CreateCommunityErrors[keyof CreateCommunityErrors];

export type CreateCommunityResponses = {
    /**
     * Community created
     */
    201: CommunityResponse;
};

export type CreateCommunityResponse = CreateCommunityResponses[keyof CreateCommunityResponses];

export type GetCommunityData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}';
};

export type GetCommunityErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not a member
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type GetCommunityError = GetCommunityErrors[keyof GetCommunityErrors];

export type GetCommunityResponses = {
    /**
     * Community
     */
    200: CommunityResponse;
};

export type GetCommunityResponse = GetCommunityResponses[keyof GetCommunityResponses];

export type UpdateCommunityData = {
    body: UpdateCommunityRequest;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}';
};

export type UpdateCommunityErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not the owner
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
    /**
     * Validation error
     */
    422: ErrorBody;
};

export type UpdateCommunityError = UpdateCommunityErrors[keyof UpdateCommunityErrors];

export type UpdateCommunityResponses = {
    /**
     * Updated community
     */
    200: CommunityResponse;
};

export type UpdateCommunityResponse = UpdateCommunityResponses[keyof UpdateCommunityResponses];

export type ListAuditEventsData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: {
        before?: string | null;
        after?: string | null;
        limit?: number | null;
        actor_account_id?: string | null;
        action?: string | null;
        space_id?: string | null;
    };
    url: '/api/v1/communities/{community_id}/audit-events';
};

export type ListAuditEventsErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type ListAuditEventsError = ListAuditEventsErrors[keyof ListAuditEventsErrors];

export type ListAuditEventsResponses = {
    /**
     * Audit page
     */
    200: AuditEventListResponse;
};

export type ListAuditEventsResponse = ListAuditEventsResponses[keyof ListAuditEventsResponses];

export type GetCommunityBannerData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/banner';
};

export type GetCommunityBannerErrors = {
    /**
     * No banner
     */
    404: ErrorBody;
};

export type GetCommunityBannerError = GetCommunityBannerErrors[keyof GetCommunityBannerErrors];

export type GetCommunityBannerResponses = {
    /**
     * Image bytes
     */
    200: Blob | File;
};

export type GetCommunityBannerResponse = GetCommunityBannerResponses[keyof GetCommunityBannerResponses];

export type UploadCommunityBannerData = {
    body?: unknown;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/banner';
};

export type UploadCommunityBannerErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not the owner
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type UploadCommunityBannerError = UploadCommunityBannerErrors[keyof UploadCommunityBannerErrors];

export type UploadCommunityBannerResponses = {
    /**
     * Updated community
     */
    200: CommunityResponse;
};

export type UploadCommunityBannerResponse = UploadCommunityBannerResponses[keyof UploadCommunityBannerResponses];

export type ListCategoriesData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: {
        space_id?: string;
    };
    url: '/api/v1/communities/{community_id}/categories';
};

export type ListCategoriesErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not a member
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type ListCategoriesError = ListCategoriesErrors[keyof ListCategoriesErrors];

export type ListCategoriesResponses = {
    /**
     * Category list
     */
    200: CategoryListResponse;
};

export type ListCategoriesResponse = ListCategoriesResponses[keyof ListCategoriesResponses];

export type CreateCategoryData = {
    body: CreateCategoryRequest;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/categories';
};

export type CreateCategoryErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type CreateCategoryError = CreateCategoryErrors[keyof CreateCategoryErrors];

export type CreateCategoryResponses = {
    /**
     * Category created
     */
    201: CategoryResponse;
};

export type CreateCategoryResponse = CreateCategoryResponses[keyof CreateCategoryResponses];

export type ReorderCategoriesData = {
    body: ReorderCategoriesRequest;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/categories/reorder';
};

export type ReorderCategoriesErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
    /**
     * Validation error
     */
    422: ErrorBody;
};

export type ReorderCategoriesError = ReorderCategoriesErrors[keyof ReorderCategoriesErrors];

export type ReorderCategoriesResponses = {
    /**
     * Reordered
     */
    200: CategoryListResponse;
};

export type ReorderCategoriesResponse = ReorderCategoriesResponses[keyof ReorderCategoriesResponses];

export type ListChannelsData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: {
        space_id?: string;
        category_id?: string;
        include_archived?: boolean;
    };
    url: '/api/v1/communities/{community_id}/channels';
};

export type ListChannelsErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not a member
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type ListChannelsError = ListChannelsErrors[keyof ListChannelsErrors];

export type ListChannelsResponses = {
    /**
     * Channel list
     */
    200: ChannelListResponse;
};

export type ListChannelsResponse = ListChannelsResponses[keyof ListChannelsResponses];

export type CreateChannelData = {
    body: CreateChannelRequest;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/channels';
};

export type CreateChannelErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type CreateChannelError = CreateChannelErrors[keyof CreateChannelErrors];

export type CreateChannelResponses = {
    /**
     * Channel created
     */
    201: ChannelResponse;
};

export type CreateChannelResponse = CreateChannelResponses[keyof CreateChannelResponses];

export type ReorderChannelsData = {
    body: ReorderChannelsRequest;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/channels/reorder';
};

export type ReorderChannelsErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
    /**
     * Validation error
     */
    422: ErrorBody;
};

export type ReorderChannelsError = ReorderChannelsErrors[keyof ReorderChannelsErrors];

export type ReorderChannelsResponses = {
    /**
     * Reordered
     */
    200: ChannelListResponse;
};

export type ReorderChannelsResponse = ReorderChannelsResponses[keyof ReorderChannelsResponses];

export type DeleteCommunityData = {
    body: DeleteCommunityRequest;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/delete';
};

export type DeleteCommunityErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not the owner
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
    /**
     * Validation error
     */
    422: ErrorBody;
};

export type DeleteCommunityError = DeleteCommunityErrors[keyof DeleteCommunityErrors];

export type DeleteCommunityResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteCommunityResponse = DeleteCommunityResponses[keyof DeleteCommunityResponses];

export type GetCommunityIconData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/icon';
};

export type GetCommunityIconErrors = {
    /**
     * No icon
     */
    404: ErrorBody;
};

export type GetCommunityIconError = GetCommunityIconErrors[keyof GetCommunityIconErrors];

export type GetCommunityIconResponses = {
    /**
     * Image bytes
     */
    200: Blob | File;
};

export type GetCommunityIconResponse = GetCommunityIconResponses[keyof GetCommunityIconResponses];

export type UploadCommunityIconData = {
    body?: unknown;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/icon';
};

export type UploadCommunityIconErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not the owner
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type UploadCommunityIconError = UploadCommunityIconErrors[keyof UploadCommunityIconErrors];

export type UploadCommunityIconResponses = {
    /**
     * Updated community
     */
    200: CommunityResponse;
};

export type UploadCommunityIconResponse = UploadCommunityIconResponses[keyof UploadCommunityIconResponses];

export type GetCommunityInviteSplashData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/invite-splash';
};

export type GetCommunityInviteSplashErrors = {
    /**
     * No splash
     */
    404: ErrorBody;
};

export type GetCommunityInviteSplashError = GetCommunityInviteSplashErrors[keyof GetCommunityInviteSplashErrors];

export type GetCommunityInviteSplashResponses = {
    /**
     * Image bytes
     */
    200: Blob | File;
};

export type GetCommunityInviteSplashResponse = GetCommunityInviteSplashResponses[keyof GetCommunityInviteSplashResponses];

export type UploadCommunityInviteSplashData = {
    body?: unknown;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/invite-splash';
};

export type UploadCommunityInviteSplashErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not the owner
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type UploadCommunityInviteSplashError = UploadCommunityInviteSplashErrors[keyof UploadCommunityInviteSplashErrors];

export type UploadCommunityInviteSplashResponses = {
    /**
     * Updated community
     */
    200: CommunityResponse;
};

export type UploadCommunityInviteSplashResponse = UploadCommunityInviteSplashResponses[keyof UploadCommunityInviteSplashResponses];

export type ListCommunityInvitesData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/invites';
};

export type ListCommunityInvitesErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Community not found
     */
    404: ErrorBody;
};

export type ListCommunityInvitesError = ListCommunityInvitesErrors[keyof ListCommunityInvitesErrors];

export type ListCommunityInvitesResponses = {
    /**
     * Invites
     */
    200: InviteListResponse;
};

export type ListCommunityInvitesResponse = ListCommunityInvitesResponses[keyof ListCommunityInvitesResponses];

export type CreateCommunityInviteData = {
    body: CreateInviteRequest;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/invites';
};

export type CreateCommunityInviteErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Community not found
     */
    404: ErrorBody;
};

export type CreateCommunityInviteError = CreateCommunityInviteErrors[keyof CreateCommunityInviteErrors];

export type CreateCommunityInviteResponses = {
    /**
     * Invite created
     */
    201: InviteResponse;
};

export type CreateCommunityInviteResponse = CreateCommunityInviteResponses[keyof CreateCommunityInviteResponses];

export type RevokeCommunityInviteData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
        /**
         * Invite id
         */
        invite_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/invites/{invite_id}';
};

export type RevokeCommunityInviteErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type RevokeCommunityInviteError = RevokeCommunityInviteErrors[keyof RevokeCommunityInviteErrors];

export type RevokeCommunityInviteResponses = {
    /**
     * Revoked
     */
    204: void;
};

export type RevokeCommunityInviteResponse = RevokeCommunityInviteResponses[keyof RevokeCommunityInviteResponses];

export type UpdateCommunityInviteData = {
    body: UpdateInviteRequest;
    path: {
        /**
         * Community id
         */
        community_id: string;
        /**
         * Invite id
         */
        invite_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/invites/{invite_id}';
};

export type UpdateCommunityInviteErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type UpdateCommunityInviteError = UpdateCommunityInviteErrors[keyof UpdateCommunityInviteErrors];

export type UpdateCommunityInviteResponses = {
    /**
     * Updated
     */
    200: InviteResponse;
};

export type UpdateCommunityInviteResponse = UpdateCommunityInviteResponses[keyof UpdateCommunityInviteResponses];

export type JoinCommunityData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/join';
};

export type JoinCommunityErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Join not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
    /**
     * Already a member
     */
    409: ErrorBody;
};

export type JoinCommunityError = JoinCommunityErrors[keyof JoinCommunityErrors];

export type JoinCommunityResponses = {
    /**
     * Joined
     */
    201: CommunityMemberResponse;
};

export type JoinCommunityResponse = JoinCommunityResponses[keyof JoinCommunityResponses];

export type LeaveCommunityData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/leave';
};

export type LeaveCommunityErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Owner cannot leave
     */
    403: ErrorBody;
    /**
     * Not a member / not found
     */
    404: ErrorBody;
};

export type LeaveCommunityError = LeaveCommunityErrors[keyof LeaveCommunityErrors];

export type LeaveCommunityResponses = {
    /**
     * Left
     */
    204: void;
};

export type LeaveCommunityResponse = LeaveCommunityResponses[keyof LeaveCommunityResponses];

export type ListCommunityMembersData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: {
        /**
         * Cursor: members after this account id
         */
        after?: string;
        /**
         * Cursor: members before this account id
         */
        before?: string;
        /**
         * Page size (1-100)
         */
        limit?: number;
    };
    url: '/api/v1/communities/{community_id}/members';
};

export type ListCommunityMembersErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not a member
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type ListCommunityMembersError = ListCommunityMembersErrors[keyof ListCommunityMembersErrors];

export type ListCommunityMembersResponses = {
    /**
     * Members page
     */
    200: CommunityMemberListResponse;
};

export type ListCommunityMembersResponse = ListCommunityMembersResponses[keyof ListCommunityMembersResponses];

export type UpdateMyCommunityNicknameData = {
    body: UpdateNicknameRequest;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/members/me';
};

export type UpdateMyCommunityNicknameErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not a member
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
    /**
     * Validation error
     */
    422: ErrorBody;
};

export type UpdateMyCommunityNicknameError = UpdateMyCommunityNicknameErrors[keyof UpdateMyCommunityNicknameErrors];

export type UpdateMyCommunityNicknameResponses = {
    /**
     * Updated membership
     */
    200: CommunityMemberResponse;
};

export type UpdateMyCommunityNicknameResponse = UpdateMyCommunityNicknameResponses[keyof UpdateMyCommunityNicknameResponses];

export type ListMemberRolesData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
        /**
         * Account id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/members/{account_id}/roles';
};

export type ListMemberRolesErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not a member
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type ListMemberRolesError = ListMemberRolesErrors[keyof ListMemberRolesErrors];

export type ListMemberRolesResponses = {
    /**
     * Member roles
     */
    200: RoleListResponse;
};

export type ListMemberRolesResponse = ListMemberRolesResponses[keyof ListMemberRolesResponses];

export type AssignMemberRoleData = {
    body: AssignRoleRequest;
    path: {
        /**
         * Community id
         */
        community_id: string;
        /**
         * Account id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/members/{account_id}/roles';
};

export type AssignMemberRoleErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type AssignMemberRoleError = AssignMemberRoleErrors[keyof AssignMemberRoleErrors];

export type AssignMemberRoleResponses = {
    /**
     * Assigned
     */
    204: void;
};

export type AssignMemberRoleResponse = AssignMemberRoleResponses[keyof AssignMemberRoleResponses];

export type RemoveMemberRoleData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
        /**
         * Account id
         */
        account_id: string;
        /**
         * Role id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/members/{account_id}/roles/{role_id}';
};

export type RemoveMemberRoleErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type RemoveMemberRoleError = RemoveMemberRoleErrors[keyof RemoveMemberRoleErrors];

export type RemoveMemberRoleResponses = {
    /**
     * Removed
     */
    204: void;
};

export type RemoveMemberRoleResponse = RemoveMemberRoleResponses[keyof RemoveMemberRoleResponses];

export type DeletePermissionOverrideData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
        /**
         * Override id
         */
        override_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/permission-overrides/{override_id}';
};

export type DeletePermissionOverrideErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type DeletePermissionOverrideError = DeletePermissionOverrideErrors[keyof DeletePermissionOverrideErrors];

export type DeletePermissionOverrideResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeletePermissionOverrideResponse = DeletePermissionOverrideResponses[keyof DeletePermissionOverrideResponses];

export type ListRoleGroupsData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/role-groups';
};

export type ListRoleGroupsErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not a member
     */
    403: ErrorBody;
};

export type ListRoleGroupsError = ListRoleGroupsErrors[keyof ListRoleGroupsErrors];

export type ListRoleGroupsResponses = {
    /**
     * Group list
     */
    200: RoleGroupListResponse;
};

export type ListRoleGroupsResponse = ListRoleGroupsResponses[keyof ListRoleGroupsResponses];

export type CreateRoleGroupData = {
    body: CreateRoleGroupRequest;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/role-groups';
};

export type CreateRoleGroupErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Name taken
     */
    409: ErrorBody;
};

export type CreateRoleGroupError = CreateRoleGroupErrors[keyof CreateRoleGroupErrors];

export type CreateRoleGroupResponses = {
    /**
     * Group created
     */
    201: RoleGroupResponse;
};

export type CreateRoleGroupResponse = CreateRoleGroupResponses[keyof CreateRoleGroupResponses];

export type BulkAssignRoleGroupData = {
    body: BulkAssignRoleGroupRequest;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/role-groups/bulk-assign';
};

export type BulkAssignRoleGroupErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
};

export type BulkAssignRoleGroupError = BulkAssignRoleGroupErrors[keyof BulkAssignRoleGroupErrors];

export type BulkAssignRoleGroupResponses = {
    /**
     * Updated roles
     */
    200: RoleListResponse;
};

export type BulkAssignRoleGroupResponse = BulkAssignRoleGroupResponses[keyof BulkAssignRoleGroupResponses];

export type ListRolesData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/roles';
};

export type ListRolesErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not a member
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type ListRolesError = ListRolesErrors[keyof ListRolesErrors];

export type ListRolesResponses = {
    /**
     * Role list
     */
    200: RoleListResponse;
};

export type ListRolesResponse = ListRolesResponses[keyof ListRolesResponses];

export type CreateRoleData = {
    body: CreateRoleRequest;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/roles';
};

export type CreateRoleErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
    /**
     * Name taken
     */
    409: ErrorBody;
};

export type CreateRoleError = CreateRoleErrors[keyof CreateRoleErrors];

export type CreateRoleResponses = {
    /**
     * Role created
     */
    201: RoleResponse;
};

export type CreateRoleResponse = CreateRoleResponses[keyof CreateRoleResponses];

export type ReorderRolesData = {
    body: ReorderRolesRequest;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/roles/reorder';
};

export type ReorderRolesErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type ReorderRolesError = ReorderRolesErrors[keyof ReorderRolesErrors];

export type ReorderRolesResponses = {
    /**
     * Reordered
     */
    200: RoleListResponse;
};

export type ReorderRolesResponse = ReorderRolesResponses[keyof ReorderRolesResponses];

export type ListSpacesData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/spaces';
};

export type ListSpacesErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not a member
     */
    403: ErrorBody;
    /**
     * Community not found
     */
    404: ErrorBody;
};

export type ListSpacesError = ListSpacesErrors[keyof ListSpacesErrors];

export type ListSpacesResponses = {
    /**
     * Space list
     */
    200: SpaceListResponse;
};

export type ListSpacesResponse = ListSpacesResponses[keyof ListSpacesResponses];

export type CreateSpaceData = {
    body: CreateSpaceRequest;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/spaces';
};

export type CreateSpaceErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Community not found
     */
    404: ErrorBody;
};

export type CreateSpaceError = CreateSpaceErrors[keyof CreateSpaceErrors];

export type CreateSpaceResponses = {
    /**
     * Space created
     */
    201: SpaceResponse;
};

export type CreateSpaceResponse = CreateSpaceResponses[keyof CreateSpaceResponses];

export type GetCommunityTagBadgeData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/tag-badge';
};

export type GetCommunityTagBadgeErrors = {
    /**
     * No badge
     */
    404: ErrorBody;
};

export type GetCommunityTagBadgeError = GetCommunityTagBadgeErrors[keyof GetCommunityTagBadgeErrors];

export type GetCommunityTagBadgeResponses = {
    /**
     * Image bytes
     */
    200: Blob | File;
};

export type GetCommunityTagBadgeResponse = GetCommunityTagBadgeResponses[keyof GetCommunityTagBadgeResponses];

export type UploadCommunityTagBadgeData = {
    body?: unknown;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/tag-badge';
};

export type UploadCommunityTagBadgeErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not the owner
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type UploadCommunityTagBadgeError = UploadCommunityTagBadgeErrors[keyof UploadCommunityTagBadgeErrors];

export type UploadCommunityTagBadgeResponses = {
    /**
     * Updated community
     */
    200: CommunityResponse;
};

export type UploadCommunityTagBadgeResponse = UploadCommunityTagBadgeResponses[keyof UploadCommunityTagBadgeResponses];

export type TransferCommunityData = {
    body: TransferCommunityRequest;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/transfer';
};

export type TransferCommunityErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not the owner
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type TransferCommunityError = TransferCommunityErrors[keyof TransferCommunityErrors];

export type TransferCommunityResponses = {
    /**
     * Ownership transferred
     */
    200: CommunityResponse;
};

export type TransferCommunityResponse = TransferCommunityResponses[keyof TransferCommunityResponses];

export type GetInstanceSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/instance/settings';
};

export type GetInstanceSettingsErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not instance admin
     */
    403: ErrorBody;
};

export type GetInstanceSettingsError = GetInstanceSettingsErrors[keyof GetInstanceSettingsErrors];

export type GetInstanceSettingsResponses = {
    /**
     * Instance settings
     */
    200: InstanceSettingsResponse;
};

export type GetInstanceSettingsResponse = GetInstanceSettingsResponses[keyof GetInstanceSettingsResponses];

export type UpdateInstanceSettingsData = {
    body: UpdateInstanceSettingsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/instance/settings';
};

export type UpdateInstanceSettingsErrors = {
    /**
     * Validation error
     */
    400: ErrorBody;
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not instance admin
     */
    403: ErrorBody;
};

export type UpdateInstanceSettingsError = UpdateInstanceSettingsErrors[keyof UpdateInstanceSettingsErrors];

export type UpdateInstanceSettingsResponses = {
    /**
     * Updated instance settings
     */
    200: InstanceSettingsResponse;
};

export type UpdateInstanceSettingsResponse = UpdateInstanceSettingsResponses[keyof UpdateInstanceSettingsResponses];

export type GetInvitePreviewData = {
    body?: never;
    path: {
        /**
         * Invite code
         */
        code: string;
    };
    query?: never;
    url: '/api/v1/invites/{code}';
};

export type GetInvitePreviewErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type GetInvitePreviewError = GetInvitePreviewErrors[keyof GetInvitePreviewErrors];

export type GetInvitePreviewResponses = {
    /**
     * Invite preview
     */
    200: InvitePreviewResponse;
};

export type GetInvitePreviewResponse = GetInvitePreviewResponses[keyof GetInvitePreviewResponses];

export type AcceptInviteData = {
    body?: never;
    path: {
        /**
         * Invite code
         */
        code: string;
    };
    query?: never;
    url: '/api/v1/invites/{code}/accept';
};

export type AcceptInviteErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Invite not usable
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
    /**
     * Already a member
     */
    409: ErrorBody;
};

export type AcceptInviteError = AcceptInviteErrors[keyof AcceptInviteErrors];

export type AcceptInviteResponses = {
    /**
     * Joined
     */
    201: CommunityMemberResponse;
};

export type AcceptInviteResponse = AcceptInviteResponses[keyof AcceptInviteResponses];

export type GetMyProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me/profile';
};

export type GetMyProfileErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
};

export type GetMyProfileError = GetMyProfileErrors[keyof GetMyProfileErrors];

export type GetMyProfileResponses = {
    /**
     * Own profile
     */
    200: ProfileResponse;
};

export type GetMyProfileResponse = GetMyProfileResponses[keyof GetMyProfileResponses];

export type UpdateMyProfileData = {
    body: UpdateProfileRequest;
    path?: never;
    query?: never;
    url: '/api/v1/me/profile';
};

export type UpdateMyProfileErrors = {
    /**
     * Validation error
     */
    400: ErrorBody;
    /**
     * Not authenticated
     */
    401: ErrorBody;
};

export type UpdateMyProfileError = UpdateMyProfileErrors[keyof UpdateMyProfileErrors];

export type UpdateMyProfileResponses = {
    /**
     * Updated profile
     */
    200: ProfileResponse;
};

export type UpdateMyProfileResponse = UpdateMyProfileResponses[keyof UpdateMyProfileResponses];

export type UploadMyAvatarData = {
    body?: unknown;
    path?: never;
    query?: never;
    url: '/api/v1/me/profile/avatar';
};

export type UploadMyAvatarErrors = {
    /**
     * Invalid or oversized image
     */
    400: ErrorBody;
    /**
     * Not authenticated
     */
    401: ErrorBody;
};

export type UploadMyAvatarError = UploadMyAvatarErrors[keyof UploadMyAvatarErrors];

export type UploadMyAvatarResponses = {
    /**
     * Updated profile
     */
    200: ProfileResponse;
};

export type UploadMyAvatarResponse = UploadMyAvatarResponses[keyof UploadMyAvatarResponses];

export type UploadMyBannerData = {
    body?: unknown;
    path?: never;
    query?: never;
    url: '/api/v1/me/profile/banner';
};

export type UploadMyBannerErrors = {
    /**
     * Invalid or oversized image
     */
    400: ErrorBody;
    /**
     * Not authenticated
     */
    401: ErrorBody;
};

export type UploadMyBannerError = UploadMyBannerErrors[keyof UploadMyBannerErrors];

export type UploadMyBannerResponses = {
    /**
     * Updated profile
     */
    200: ProfileResponse;
};

export type UploadMyBannerResponse = UploadMyBannerResponses[keyof UploadMyBannerResponses];

export type GetMetaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/meta';
};

export type GetMetaResponses = {
    /**
     * Instance name and version
     */
    200: MetaResponse;
};

export type GetMetaResponse = GetMetaResponses[keyof GetMetaResponses];

export type ExplainPermissionData = {
    body: ExplainPermissionRequest;
    path?: never;
    query?: never;
    url: '/api/v1/permissions/explain';
};

export type ExplainPermissionErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type ExplainPermissionError = ExplainPermissionErrors[keyof ExplainPermissionErrors];

export type ExplainPermissionResponses = {
    /**
     * Explanation
     */
    200: ExplainPermissionResponse;
};

export type ExplainPermissionResponse2 = ExplainPermissionResponses[keyof ExplainPermissionResponses];

export type ViewAsChannelsData = {
    body: ViewAsChannelsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/permissions/view-as/channels';
};

export type ViewAsChannelsErrors = {
    /**
     * Invalid request
     */
    400: ErrorBody;
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type ViewAsChannelsError = ViewAsChannelsErrors[keyof ViewAsChannelsErrors];

export type ViewAsChannelsResponses = {
    /**
     * Simulated channel list
     */
    200: ViewAsChannelsResponse;
};

export type ViewAsChannelsResponse2 = ViewAsChannelsResponses[keyof ViewAsChannelsResponses];

export type ListPresenceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/presence';
};

export type ListPresenceErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
};

export type ListPresenceError = ListPresenceErrors[keyof ListPresenceErrors];

export type ListPresenceResponses = {
    /**
     * Online accounts
     */
    200: PresenceListResponse;
};

export type ListPresenceResponse = ListPresenceResponses[keyof ListPresenceResponses];

export type GetProfileData = {
    body?: never;
    path: {
        /**
         * Account id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/profiles/{account_id}';
};

export type GetProfileErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type GetProfileError = GetProfileErrors[keyof GetProfileErrors];

export type GetProfileResponses = {
    /**
     * Profile
     */
    200: ProfileResponse;
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type GetProfileAvatarData = {
    body?: never;
    path: {
        /**
         * Account id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/profiles/{account_id}/avatar';
};

export type GetProfileAvatarErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type GetProfileAvatarError = GetProfileAvatarErrors[keyof GetProfileAvatarErrors];

export type GetProfileAvatarResponses = {
    /**
     * Image bytes
     */
    200: unknown;
};

export type GetProfileBannerData = {
    body?: never;
    path: {
        /**
         * Account id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/profiles/{account_id}/banner';
};

export type GetProfileBannerErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type GetProfileBannerError = GetProfileBannerErrors[keyof GetProfileBannerErrors];

export type GetProfileBannerResponses = {
    /**
     * Image bytes
     */
    200: unknown;
};

export type DeleteRoleGroupData = {
    body?: never;
    path: {
        /**
         * Group id
         */
        group_id: string;
    };
    query?: never;
    url: '/api/v1/role-groups/{group_id}';
};

export type DeleteRoleGroupErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type DeleteRoleGroupError = DeleteRoleGroupErrors[keyof DeleteRoleGroupErrors];

export type DeleteRoleGroupResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteRoleGroupResponse = DeleteRoleGroupResponses[keyof DeleteRoleGroupResponses];

export type UpdateRoleGroupData = {
    body: UpdateRoleGroupRequest;
    path: {
        /**
         * Group id
         */
        group_id: string;
    };
    query?: never;
    url: '/api/v1/role-groups/{group_id}';
};

export type UpdateRoleGroupErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type UpdateRoleGroupError = UpdateRoleGroupErrors[keyof UpdateRoleGroupErrors];

export type UpdateRoleGroupResponses = {
    /**
     * Updated group
     */
    200: RoleGroupResponse;
};

export type UpdateRoleGroupResponse = UpdateRoleGroupResponses[keyof UpdateRoleGroupResponses];

export type DeleteRoleData = {
    body?: never;
    path: {
        /**
         * Role id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/roles/{role_id}';
};

export type DeleteRoleErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type DeleteRoleError = DeleteRoleErrors[keyof DeleteRoleErrors];

export type DeleteRoleResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteRoleResponse = DeleteRoleResponses[keyof DeleteRoleResponses];

export type GetRoleData = {
    body?: never;
    path: {
        /**
         * Role id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/roles/{role_id}';
};

export type GetRoleErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not a member
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type GetRoleError = GetRoleErrors[keyof GetRoleErrors];

export type GetRoleResponses = {
    /**
     * Role
     */
    200: RoleResponse;
};

export type GetRoleResponse = GetRoleResponses[keyof GetRoleResponses];

export type UpdateRoleData = {
    body: UpdateRoleRequest;
    path: {
        /**
         * Role id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/roles/{role_id}';
};

export type UpdateRoleErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type UpdateRoleError = UpdateRoleErrors[keyof UpdateRoleErrors];

export type UpdateRoleResponses = {
    /**
     * Updated role
     */
    200: RoleResponse;
};

export type UpdateRoleResponse = UpdateRoleResponses[keyof UpdateRoleResponses];

export type CloneRoleData = {
    body?: never;
    path: {
        /**
         * Role id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/roles/{role_id}/clone';
};

export type CloneRoleErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type CloneRoleError = CloneRoleErrors[keyof CloneRoleErrors];

export type CloneRoleResponses = {
    /**
     * Cloned role
     */
    201: RoleResponse;
};

export type CloneRoleResponse = CloneRoleResponses[keyof CloneRoleResponses];

export type DeleteRoleIconData = {
    body?: never;
    path: {
        /**
         * Role id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/roles/{role_id}/icon';
};

export type DeleteRoleIconErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type DeleteRoleIconError = DeleteRoleIconErrors[keyof DeleteRoleIconErrors];

export type DeleteRoleIconResponses = {
    /**
     * Updated role
     */
    200: RoleResponse;
};

export type DeleteRoleIconResponse = DeleteRoleIconResponses[keyof DeleteRoleIconResponses];

export type GetRoleIconData = {
    body?: never;
    path: {
        /**
         * Role id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/roles/{role_id}/icon';
};

export type GetRoleIconErrors = {
    /**
     * Not found
     */
    404: ErrorBody;
};

export type GetRoleIconError = GetRoleIconErrors[keyof GetRoleIconErrors];

export type GetRoleIconResponses = {
    /**
     * Image bytes
     */
    200: unknown;
};

export type UploadRoleIconData = {
    body?: unknown;
    path: {
        /**
         * Role id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/roles/{role_id}/icon';
};

export type UploadRoleIconErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
    /**
     * Validation error
     */
    422: ErrorBody;
};

export type UploadRoleIconError = UploadRoleIconErrors[keyof UploadRoleIconErrors];

export type UploadRoleIconResponses = {
    /**
     * Updated role
     */
    200: RoleResponse;
};

export type UploadRoleIconResponse = UploadRoleIconResponses[keyof UploadRoleIconResponses];

export type DeleteSpaceData = {
    body?: never;
    path: {
        /**
         * Space id
         */
        space_id: string;
    };
    query?: never;
    url: '/api/v1/spaces/{space_id}';
};

export type DeleteSpaceErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type DeleteSpaceError = DeleteSpaceErrors[keyof DeleteSpaceErrors];

export type DeleteSpaceResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteSpaceResponse = DeleteSpaceResponses[keyof DeleteSpaceResponses];

export type GetSpaceData = {
    body?: never;
    path: {
        /**
         * Space id
         */
        space_id: string;
    };
    query?: never;
    url: '/api/v1/spaces/{space_id}';
};

export type GetSpaceErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not a member
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type GetSpaceError = GetSpaceErrors[keyof GetSpaceErrors];

export type GetSpaceResponses = {
    /**
     * Space
     */
    200: SpaceResponse;
};

export type GetSpaceResponse = GetSpaceResponses[keyof GetSpaceResponses];

export type UpdateSpaceData = {
    body: UpdateSpaceRequest;
    path: {
        /**
         * Space id
         */
        space_id: string;
    };
    query?: never;
    url: '/api/v1/spaces/{space_id}';
};

export type UpdateSpaceErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type UpdateSpaceError = UpdateSpaceErrors[keyof UpdateSpaceErrors];

export type UpdateSpaceResponses = {
    /**
     * Updated space
     */
    200: SpaceResponse;
};

export type UpdateSpaceResponse = UpdateSpaceResponses[keyof UpdateSpaceResponses];

export type JoinSpaceData = {
    body?: never;
    path: {
        /**
         * Space id
         */
        space_id: string;
    };
    query?: never;
    url: '/api/v1/spaces/{space_id}/join';
};

export type JoinSpaceErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Join not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
    /**
     * Already a member
     */
    409: ErrorBody;
};

export type JoinSpaceError = JoinSpaceErrors[keyof JoinSpaceErrors];

export type JoinSpaceResponses = {
    /**
     * Joined
     */
    201: SpaceMemberResponse;
};

export type JoinSpaceResponse = JoinSpaceResponses[keyof JoinSpaceResponses];

export type LeaveSpaceData = {
    body?: never;
    path: {
        /**
         * Space id
         */
        space_id: string;
    };
    query?: never;
    url: '/api/v1/spaces/{space_id}/leave';
};

export type LeaveSpaceErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not a member or not found
     */
    404: ErrorBody;
};

export type LeaveSpaceError = LeaveSpaceErrors[keyof LeaveSpaceErrors];

export type LeaveSpaceResponses = {
    /**
     * Left
     */
    204: void;
};

export type LeaveSpaceResponse = LeaveSpaceResponses[keyof LeaveSpaceResponses];

export type ListSpaceMembersData = {
    body?: never;
    path: {
        /**
         * Space id
         */
        space_id: string;
    };
    query?: never;
    url: '/api/v1/spaces/{space_id}/members';
};

export type ListSpaceMembersErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type ListSpaceMembersError = ListSpaceMembersErrors[keyof ListSpaceMembersErrors];

export type ListSpaceMembersResponses = {
    /**
     * Members
     */
    200: SpaceMemberListResponse;
};

export type ListSpaceMembersResponse = ListSpaceMembersResponses[keyof ListSpaceMembersResponses];

export type AddSpaceMemberData = {
    body: AddSpaceMemberRequest;
    path: {
        /**
         * Space id
         */
        space_id: string;
    };
    query?: never;
    url: '/api/v1/spaces/{space_id}/members';
};

export type AddSpaceMemberErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
    /**
     * Already a member
     */
    409: ErrorBody;
};

export type AddSpaceMemberError = AddSpaceMemberErrors[keyof AddSpaceMemberErrors];

export type AddSpaceMemberResponses = {
    /**
     * Member added
     */
    201: SpaceMemberResponse;
};

export type AddSpaceMemberResponse = AddSpaceMemberResponses[keyof AddSpaceMemberResponses];

export type RemoveSpaceMemberData = {
    body?: never;
    path: {
        /**
         * Space id
         */
        space_id: string;
        /**
         * Account id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/spaces/{space_id}/members/{account_id}';
};

export type RemoveSpaceMemberErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type RemoveSpaceMemberError = RemoveSpaceMemberErrors[keyof RemoveSpaceMemberErrors];

export type RemoveSpaceMemberResponses = {
    /**
     * Removed
     */
    204: void;
};

export type RemoveSpaceMemberResponse = RemoveSpaceMemberResponses[keyof RemoveSpaceMemberResponses];
