// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Public account fields (never includes password hash).
 */
export type AccountResponse = {
    email?: string | null;
    id: string;
    is_bot: boolean;
    is_instance_admin: boolean;
};

/**
 * Authenticated session payload.
 */
export type AuthSessionResponse = {
    account: AccountResponse;
};

/**
 * Change email (requires current password; applied immediately until F117 adds confirmation mail).
 */
export type ChangeEmailRequest = {
    current_password: string;
    email: string;
};

/**
 * Change password (requires current password).
 */
export type ChangePasswordRequest = {
    current_password: string;
    new_password: string;
    /**
     * When true, delete all other sessions for this account (current session stays).
     */
    revoke_other_sessions?: boolean | null;
};

/**
 * Who may create communities on this instance.
 */
export type CommunityCreationMode = 'open' | 'admin_only' | 'single';

/**
 * List wrapper for communities the caller belongs to.
 */
export type CommunityListResponse = {
    communities: Array<CommunityResponse>;
};

/**
 * Cursor page of community members.
 */
export type CommunityMemberListResponse = {
    has_more: boolean;
    items: Array<CommunityMemberResponse>;
};

/**
 * One community member with profile display fields.
 */
export type CommunityMemberResponse = {
    account_id: string;
    avatar_url?: string | null;
    community_id: string;
    display_name: string;
    has_avatar: boolean;
    joined_at: string;
    nickname: string;
    role: CommunityMemberRole;
};

/**
 * Membership role within a community.
 */
export type CommunityMemberRole = 'owner' | 'member';

/**
 * Public community representation.
 */
export type CommunityResponse = {
    banner_url?: string | null;
    created_at: string;
    description: string;
    discoverable_on_instance: boolean;
    icon_url?: string | null;
    id: string;
    join_mode: JoinMode;
    name: string;
    owner_account_id: string;
    slug: string;
    timezone: string;
    updated_at: string;
};

/**
 * Create a community.
 */
export type CreateCommunityRequest = {
    description?: string | null;
    discoverable_on_instance?: boolean | null;
    join_mode?: null | JoinMode;
    name: string;
    slug?: string | null;
    timezone?: string | null;
};

/**
 * Create a community invite.
 */
export type CreateInviteRequest = {
    expire_after?: null | InviteExpireAfter;
    /**
     * `null` / omitted = unlimited. Otherwise `1..=1000`.
     */
    max_uses?: number | null;
};

/**
 * Create a Space in a community.
 */
export type CreateSpaceRequest = {
    description?: string | null;
    game?: string | null;
    name: string;
    topic?: string | null;
    visibility?: null | SpaceVisibility;
};

/**
 * JSON error envelope for `/api/v1` and unknown routes.
 */
export type ErrorBody = {
    code: string;
    details?: {
        [key: string]: unknown;
    } | null;
    message: string;
    request_id: string;
};

/**
 * Instance settings visible to instance admins.
 */
export type InstanceSettingsResponse = {
    community_creation_mode: CommunityCreationMode;
    /**
     * When true, [`UpdateInstanceSettingsRequest::community_creation_mode`] is ignored.
     */
    community_creation_mode_locked: boolean;
    id: string;
    name: string;
    oidc_client_id?: string | null;
    oidc_enabled: boolean;
    oidc_issuer?: string | null;
    public_url: string;
    registration_mode: RegistrationMode;
    updated_at: string;
};

/**
 * Relative invite lifetime chosen before code generation.
 */
export type InviteExpireAfter = {
    unit: InviteExpireUnit;
    value: number;
};

/**
 * Units for [`InviteExpireAfter`].
 */
export type InviteExpireUnit = 'hours' | 'days' | 'months';

/**
 * List of invites for a community.
 */
export type InviteListResponse = {
    invites: Array<InviteResponse>;
};

/**
 * Preview for join-by-code UI (no sensitive creator detail beyond community).
 */
export type InvitePreviewResponse = {
    code: string;
    community_id: string;
    community_name: string;
    community_slug: string;
    exhausted: boolean;
    expired: boolean;
    paused: boolean;
};

/**
 * Public invite representation.
 */
export type InviteResponse = {
    code: string;
    community_id: string;
    created_at: string;
    created_by: string;
    expires_at?: string | null;
    id: string;
    max_uses?: number | null;
    paused: boolean;
    revoked_at?: string | null;
    uses: number;
};

/**
 * How accounts may join a community (invites/applications expand in later features).
 */
export type JoinMode = 'open' | 'invite' | 'application';

/**
 * Login with email and password.
 */
export type LoginRequest = {
    email: string;
    password: string;
};

/**
 * Build, version, and public instance policy flags for the SPA.
 */
export type MetaResponse = {
    community_creation_mode: CommunityCreationMode;
    name: string;
    /**
     * Whether SSO sign-in is configured and enabled for this instance.
     */
    oidc_enabled: boolean;
    /**
     * Whether email/password login and registration are offered.
     */
    password_login_enabled: boolean;
    registration_mode: RegistrationMode;
    version: string;
};

/**
 * Instance-wide presence snapshot (F018).
 */
export type PresenceEntry = {
    account_id: string;
    custom_status: string;
    status: PublicPresenceStatus;
};

/**
 * Online users visible on this instance.
 */
export type PresenceListResponse = {
    presences: Array<PresenceEntry>;
};

/**
 * Stored preference and gateway-reported status while connected.
 */
export type PresenceStatus = 'online' | 'idle' | 'dnd' | 'invisible';

/**
 * Public profile fields.
 */
export type ProfileResponse = {
    account_id: string;
    avatar_url?: string | null;
    banner_url?: string | null;
    bio: string;
    custom_status: string;
    display_name: string;
    has_avatar: boolean;
    has_banner: boolean;
    presence_status: PublicPresenceStatus;
};

/**
 * Presence exposed to clients (offline when disconnected or hidden from viewers).
 */
export type PublicPresenceStatus = 'online' | 'idle' | 'dnd' | 'invisible' | 'offline';

/**
 * Register with email, password, and display name.
 */
export type RegisterRequest = {
    display_name: string;
    email: string;
    password: string;
};

/**
 * Who may register new local accounts on this instance.
 */
export type RegistrationMode = 'open' | 'invite' | 'closed';

/**
 * Spaces in a community, ordered by position.
 */
export type SpaceListResponse = {
    spaces: Array<SpaceResponse>;
};

/**
 * Public Space representation.
 */
export type SpaceResponse = {
    community_id: string;
    created_at: string;
    description: string;
    game: string;
    icon_url?: string | null;
    id: string;
    name: string;
    position: number;
    topic: string;
    updated_at: string;
    visibility: SpaceVisibility;
};

/**
 * Who can see / enter a Space (F023 membership expands access rules).
 */
export type SpaceVisibility = 'open' | 'restricted';

/**
 * Update community settings (owner).
 */
export type UpdateCommunityRequest = {
    description?: string | null;
    discoverable_on_instance?: boolean | null;
    join_mode?: null | JoinMode;
    name?: string | null;
    timezone?: string | null;
};

/**
 * Partial update of instance settings (instance admin only).
 */
export type UpdateInstanceSettingsRequest = {
    community_creation_mode?: null | CommunityCreationMode;
    name?: string | null;
    oidc_client_id?: string | null;
    oidc_enabled?: boolean | null;
    oidc_issuer?: string | null;
    public_url?: string | null;
    registration_mode?: null | RegistrationMode;
};

/**
 * Pause / unpause an invite.
 */
export type UpdateInviteRequest = {
    paused?: boolean | null;
};

/**
 * Update the caller's nickname in a community.
 */
export type UpdateNicknameRequest = {
    nickname: string;
};

/**
 * Patch display name, bio, presence, and/or custom status.
 */
export type UpdateProfileRequest = {
    bio?: string | null;
    custom_status?: string | null;
    /**
     * Empty string is allowed (new accounts start blank until set).
     */
    display_name?: string | null;
    presence_status?: null | PresenceStatus;
};

/**
 * Update Space settings.
 */
export type UpdateSpaceRequest = {
    description?: string | null;
    game?: string | null;
    name?: string | null;
    position?: number | null;
    topic?: string | null;
    visibility?: null | SpaceVisibility;
};

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginErrors = {
    /**
     * Validation error
     */
    400: ErrorBody;
    /**
     * Invalid credentials
     */
    401: ErrorBody;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Logged in
     */
    200: AuthSessionResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutResponses = {
    /**
     * Logged out
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type GetMeErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * Current account
     */
    200: AuthSessionResponse;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type ChangeMyEmailData = {
    body: ChangeEmailRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me/email';
};

export type ChangeMyEmailErrors = {
    /**
     * Validation error
     */
    400: ErrorBody;
    /**
     * Wrong current password or not authenticated
     */
    401: ErrorBody;
    /**
     * Email taken
     */
    409: ErrorBody;
};

export type ChangeMyEmailError = ChangeMyEmailErrors[keyof ChangeMyEmailErrors];

export type ChangeMyEmailResponses = {
    /**
     * Email updated
     */
    200: AuthSessionResponse;
};

export type ChangeMyEmailResponse = ChangeMyEmailResponses[keyof ChangeMyEmailResponses];

export type ChangeMyPasswordData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me/password';
};

export type ChangeMyPasswordErrors = {
    /**
     * Validation error
     */
    400: ErrorBody;
    /**
     * Wrong current password or not authenticated
     */
    401: ErrorBody;
};

export type ChangeMyPasswordError = ChangeMyPasswordErrors[keyof ChangeMyPasswordErrors];

export type ChangeMyPasswordResponses = {
    /**
     * Password updated
     */
    204: void;
};

export type ChangeMyPasswordResponse = ChangeMyPasswordResponses[keyof ChangeMyPasswordResponses];

export type OidcCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/oidc/callback';
};

export type OidcCallbackErrors = {
    /**
     * Invalid callback
     */
    400: ErrorBody;
    /**
     * OIDC not configured
     */
    404: ErrorBody;
};

export type OidcCallbackError = OidcCallbackErrors[keyof OidcCallbackErrors];

export type OidcCallbackResponses = {
    /**
     * HTML bounce to SPA with session cookie
     */
    200: unknown;
};

export type StartOidcLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/oidc/start';
};

export type StartOidcLoginErrors = {
    /**
     * OIDC not configured
     */
    404: ErrorBody;
    /**
     * Internal error
     */
    500: ErrorBody;
};

export type StartOidcLoginError = StartOidcLoginErrors[keyof StartOidcLoginErrors];

export type StartOidcLoginResponses = {
    /**
     * HTML bounce to OIDC provider
     */
    200: unknown;
};

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterErrors = {
    /**
     * Validation error
     */
    400: ErrorBody;
    /**
     * Registration closed or CSRF
     */
    403: ErrorBody;
    /**
     * Email taken
     */
    409: ErrorBody;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Account created
     */
    201: AuthSessionResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type ListCommunitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/communities';
};

export type ListCommunitiesErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
};

export type ListCommunitiesError = ListCommunitiesErrors[keyof ListCommunitiesErrors];

export type ListCommunitiesResponses = {
    /**
     * Membership communities
     */
    200: CommunityListResponse;
};

export type ListCommunitiesResponse = ListCommunitiesResponses[keyof ListCommunitiesResponses];

export type CreateCommunityData = {
    body: CreateCommunityRequest;
    path?: never;
    query?: never;
    url: '/api/v1/communities';
};

export type CreateCommunityErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Creation disallowed by instance policy
     */
    403: ErrorBody;
    /**
     * Slug conflict
     */
    409: ErrorBody;
    /**
     * Validation error
     */
    422: ErrorBody;
};

export type CreateCommunityError = CreateCommunityErrors[keyof CreateCommunityErrors];

export type CreateCommunityResponses = {
    /**
     * Community created
     */
    201: CommunityResponse;
};

export type CreateCommunityResponse = CreateCommunityResponses[keyof CreateCommunityResponses];

export type GetCommunityData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}';
};

export type GetCommunityErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not a member
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type GetCommunityError = GetCommunityErrors[keyof GetCommunityErrors];

export type GetCommunityResponses = {
    /**
     * Community
     */
    200: CommunityResponse;
};

export type GetCommunityResponse = GetCommunityResponses[keyof GetCommunityResponses];

export type UpdateCommunityData = {
    body: UpdateCommunityRequest;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}';
};

export type UpdateCommunityErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not the owner
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
    /**
     * Validation error
     */
    422: ErrorBody;
};

export type UpdateCommunityError = UpdateCommunityErrors[keyof UpdateCommunityErrors];

export type UpdateCommunityResponses = {
    /**
     * Updated community
     */
    200: CommunityResponse;
};

export type UpdateCommunityResponse = UpdateCommunityResponses[keyof UpdateCommunityResponses];

export type GetCommunityBannerData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/banner';
};

export type GetCommunityBannerErrors = {
    /**
     * No banner
     */
    404: ErrorBody;
};

export type GetCommunityBannerError = GetCommunityBannerErrors[keyof GetCommunityBannerErrors];

export type GetCommunityBannerResponses = {
    /**
     * Image bytes
     */
    200: Blob | File;
};

export type GetCommunityBannerResponse = GetCommunityBannerResponses[keyof GetCommunityBannerResponses];

export type UploadCommunityBannerData = {
    body?: unknown;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/banner';
};

export type UploadCommunityBannerErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not the owner
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type UploadCommunityBannerError = UploadCommunityBannerErrors[keyof UploadCommunityBannerErrors];

export type UploadCommunityBannerResponses = {
    /**
     * Updated community
     */
    200: CommunityResponse;
};

export type UploadCommunityBannerResponse = UploadCommunityBannerResponses[keyof UploadCommunityBannerResponses];

export type GetCommunityIconData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/icon';
};

export type GetCommunityIconErrors = {
    /**
     * No icon
     */
    404: ErrorBody;
};

export type GetCommunityIconError = GetCommunityIconErrors[keyof GetCommunityIconErrors];

export type GetCommunityIconResponses = {
    /**
     * Image bytes
     */
    200: Blob | File;
};

export type GetCommunityIconResponse = GetCommunityIconResponses[keyof GetCommunityIconResponses];

export type UploadCommunityIconData = {
    body?: unknown;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/icon';
};

export type UploadCommunityIconErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not the owner
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type UploadCommunityIconError = UploadCommunityIconErrors[keyof UploadCommunityIconErrors];

export type UploadCommunityIconResponses = {
    /**
     * Updated community
     */
    200: CommunityResponse;
};

export type UploadCommunityIconResponse = UploadCommunityIconResponses[keyof UploadCommunityIconResponses];

export type ListCommunityInvitesData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/invites';
};

export type ListCommunityInvitesErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Community not found
     */
    404: ErrorBody;
};

export type ListCommunityInvitesError = ListCommunityInvitesErrors[keyof ListCommunityInvitesErrors];

export type ListCommunityInvitesResponses = {
    /**
     * Invites
     */
    200: InviteListResponse;
};

export type ListCommunityInvitesResponse = ListCommunityInvitesResponses[keyof ListCommunityInvitesResponses];

export type CreateCommunityInviteData = {
    body: CreateInviteRequest;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/invites';
};

export type CreateCommunityInviteErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Community not found
     */
    404: ErrorBody;
};

export type CreateCommunityInviteError = CreateCommunityInviteErrors[keyof CreateCommunityInviteErrors];

export type CreateCommunityInviteResponses = {
    /**
     * Invite created
     */
    201: InviteResponse;
};

export type CreateCommunityInviteResponse = CreateCommunityInviteResponses[keyof CreateCommunityInviteResponses];

export type RevokeCommunityInviteData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
        /**
         * Invite id
         */
        invite_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/invites/{invite_id}';
};

export type RevokeCommunityInviteErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type RevokeCommunityInviteError = RevokeCommunityInviteErrors[keyof RevokeCommunityInviteErrors];

export type RevokeCommunityInviteResponses = {
    /**
     * Revoked
     */
    204: void;
};

export type RevokeCommunityInviteResponse = RevokeCommunityInviteResponses[keyof RevokeCommunityInviteResponses];

export type UpdateCommunityInviteData = {
    body: UpdateInviteRequest;
    path: {
        /**
         * Community id
         */
        community_id: string;
        /**
         * Invite id
         */
        invite_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/invites/{invite_id}';
};

export type UpdateCommunityInviteErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type UpdateCommunityInviteError = UpdateCommunityInviteErrors[keyof UpdateCommunityInviteErrors];

export type UpdateCommunityInviteResponses = {
    /**
     * Updated
     */
    200: InviteResponse;
};

export type UpdateCommunityInviteResponse = UpdateCommunityInviteResponses[keyof UpdateCommunityInviteResponses];

export type JoinCommunityData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/join';
};

export type JoinCommunityErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Join not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
    /**
     * Already a member
     */
    409: ErrorBody;
};

export type JoinCommunityError = JoinCommunityErrors[keyof JoinCommunityErrors];

export type JoinCommunityResponses = {
    /**
     * Joined
     */
    201: CommunityMemberResponse;
};

export type JoinCommunityResponse = JoinCommunityResponses[keyof JoinCommunityResponses];

export type LeaveCommunityData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/leave';
};

export type LeaveCommunityErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Owner cannot leave
     */
    403: ErrorBody;
    /**
     * Not a member / not found
     */
    404: ErrorBody;
};

export type LeaveCommunityError = LeaveCommunityErrors[keyof LeaveCommunityErrors];

export type LeaveCommunityResponses = {
    /**
     * Left
     */
    204: void;
};

export type LeaveCommunityResponse = LeaveCommunityResponses[keyof LeaveCommunityResponses];

export type ListCommunityMembersData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: {
        /**
         * Cursor: members after this account id
         */
        after?: string;
        /**
         * Cursor: members before this account id
         */
        before?: string;
        /**
         * Page size (1-100)
         */
        limit?: number;
    };
    url: '/api/v1/communities/{community_id}/members';
};

export type ListCommunityMembersErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not a member
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type ListCommunityMembersError = ListCommunityMembersErrors[keyof ListCommunityMembersErrors];

export type ListCommunityMembersResponses = {
    /**
     * Members page
     */
    200: CommunityMemberListResponse;
};

export type ListCommunityMembersResponse = ListCommunityMembersResponses[keyof ListCommunityMembersResponses];

export type UpdateMyCommunityNicknameData = {
    body: UpdateNicknameRequest;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/members/me';
};

export type UpdateMyCommunityNicknameErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not a member
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
    /**
     * Validation error
     */
    422: ErrorBody;
};

export type UpdateMyCommunityNicknameError = UpdateMyCommunityNicknameErrors[keyof UpdateMyCommunityNicknameErrors];

export type UpdateMyCommunityNicknameResponses = {
    /**
     * Updated membership
     */
    200: CommunityMemberResponse;
};

export type UpdateMyCommunityNicknameResponse = UpdateMyCommunityNicknameResponses[keyof UpdateMyCommunityNicknameResponses];

export type ListSpacesData = {
    body?: never;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/spaces';
};

export type ListSpacesErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not a member
     */
    403: ErrorBody;
    /**
     * Community not found
     */
    404: ErrorBody;
};

export type ListSpacesError = ListSpacesErrors[keyof ListSpacesErrors];

export type ListSpacesResponses = {
    /**
     * Space list
     */
    200: SpaceListResponse;
};

export type ListSpacesResponse = ListSpacesResponses[keyof ListSpacesResponses];

export type CreateSpaceData = {
    body: CreateSpaceRequest;
    path: {
        /**
         * Community id
         */
        community_id: string;
    };
    query?: never;
    url: '/api/v1/communities/{community_id}/spaces';
};

export type CreateSpaceErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Community not found
     */
    404: ErrorBody;
};

export type CreateSpaceError = CreateSpaceErrors[keyof CreateSpaceErrors];

export type CreateSpaceResponses = {
    /**
     * Space created
     */
    201: SpaceResponse;
};

export type CreateSpaceResponse = CreateSpaceResponses[keyof CreateSpaceResponses];

export type GetInstanceSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/instance/settings';
};

export type GetInstanceSettingsErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not instance admin
     */
    403: ErrorBody;
};

export type GetInstanceSettingsError = GetInstanceSettingsErrors[keyof GetInstanceSettingsErrors];

export type GetInstanceSettingsResponses = {
    /**
     * Instance settings
     */
    200: InstanceSettingsResponse;
};

export type GetInstanceSettingsResponse = GetInstanceSettingsResponses[keyof GetInstanceSettingsResponses];

export type UpdateInstanceSettingsData = {
    body: UpdateInstanceSettingsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/instance/settings';
};

export type UpdateInstanceSettingsErrors = {
    /**
     * Validation error
     */
    400: ErrorBody;
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not instance admin
     */
    403: ErrorBody;
};

export type UpdateInstanceSettingsError = UpdateInstanceSettingsErrors[keyof UpdateInstanceSettingsErrors];

export type UpdateInstanceSettingsResponses = {
    /**
     * Updated instance settings
     */
    200: InstanceSettingsResponse;
};

export type UpdateInstanceSettingsResponse = UpdateInstanceSettingsResponses[keyof UpdateInstanceSettingsResponses];

export type GetInvitePreviewData = {
    body?: never;
    path: {
        /**
         * Invite code
         */
        code: string;
    };
    query?: never;
    url: '/api/v1/invites/{code}';
};

export type GetInvitePreviewErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type GetInvitePreviewError = GetInvitePreviewErrors[keyof GetInvitePreviewErrors];

export type GetInvitePreviewResponses = {
    /**
     * Invite preview
     */
    200: InvitePreviewResponse;
};

export type GetInvitePreviewResponse = GetInvitePreviewResponses[keyof GetInvitePreviewResponses];

export type AcceptInviteData = {
    body?: never;
    path: {
        /**
         * Invite code
         */
        code: string;
    };
    query?: never;
    url: '/api/v1/invites/{code}/accept';
};

export type AcceptInviteErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Invite not usable
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
    /**
     * Already a member
     */
    409: ErrorBody;
};

export type AcceptInviteError = AcceptInviteErrors[keyof AcceptInviteErrors];

export type AcceptInviteResponses = {
    /**
     * Joined
     */
    201: CommunityMemberResponse;
};

export type AcceptInviteResponse = AcceptInviteResponses[keyof AcceptInviteResponses];

export type GetMyProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me/profile';
};

export type GetMyProfileErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
};

export type GetMyProfileError = GetMyProfileErrors[keyof GetMyProfileErrors];

export type GetMyProfileResponses = {
    /**
     * Own profile
     */
    200: ProfileResponse;
};

export type GetMyProfileResponse = GetMyProfileResponses[keyof GetMyProfileResponses];

export type UpdateMyProfileData = {
    body: UpdateProfileRequest;
    path?: never;
    query?: never;
    url: '/api/v1/me/profile';
};

export type UpdateMyProfileErrors = {
    /**
     * Validation error
     */
    400: ErrorBody;
    /**
     * Not authenticated
     */
    401: ErrorBody;
};

export type UpdateMyProfileError = UpdateMyProfileErrors[keyof UpdateMyProfileErrors];

export type UpdateMyProfileResponses = {
    /**
     * Updated profile
     */
    200: ProfileResponse;
};

export type UpdateMyProfileResponse = UpdateMyProfileResponses[keyof UpdateMyProfileResponses];

export type UploadMyAvatarData = {
    body?: unknown;
    path?: never;
    query?: never;
    url: '/api/v1/me/profile/avatar';
};

export type UploadMyAvatarErrors = {
    /**
     * Invalid or oversized image
     */
    400: ErrorBody;
    /**
     * Not authenticated
     */
    401: ErrorBody;
};

export type UploadMyAvatarError = UploadMyAvatarErrors[keyof UploadMyAvatarErrors];

export type UploadMyAvatarResponses = {
    /**
     * Updated profile
     */
    200: ProfileResponse;
};

export type UploadMyAvatarResponse = UploadMyAvatarResponses[keyof UploadMyAvatarResponses];

export type UploadMyBannerData = {
    body?: unknown;
    path?: never;
    query?: never;
    url: '/api/v1/me/profile/banner';
};

export type UploadMyBannerErrors = {
    /**
     * Invalid or oversized image
     */
    400: ErrorBody;
    /**
     * Not authenticated
     */
    401: ErrorBody;
};

export type UploadMyBannerError = UploadMyBannerErrors[keyof UploadMyBannerErrors];

export type UploadMyBannerResponses = {
    /**
     * Updated profile
     */
    200: ProfileResponse;
};

export type UploadMyBannerResponse = UploadMyBannerResponses[keyof UploadMyBannerResponses];

export type GetMetaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/meta';
};

export type GetMetaResponses = {
    /**
     * Instance name and version
     */
    200: MetaResponse;
};

export type GetMetaResponse = GetMetaResponses[keyof GetMetaResponses];

export type ListPresenceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/presence';
};

export type ListPresenceErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
};

export type ListPresenceError = ListPresenceErrors[keyof ListPresenceErrors];

export type ListPresenceResponses = {
    /**
     * Online accounts
     */
    200: PresenceListResponse;
};

export type ListPresenceResponse = ListPresenceResponses[keyof ListPresenceResponses];

export type GetProfileData = {
    body?: never;
    path: {
        /**
         * Account id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/profiles/{account_id}';
};

export type GetProfileErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type GetProfileError = GetProfileErrors[keyof GetProfileErrors];

export type GetProfileResponses = {
    /**
     * Profile
     */
    200: ProfileResponse;
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type GetProfileAvatarData = {
    body?: never;
    path: {
        /**
         * Account id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/profiles/{account_id}/avatar';
};

export type GetProfileAvatarErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type GetProfileAvatarError = GetProfileAvatarErrors[keyof GetProfileAvatarErrors];

export type GetProfileAvatarResponses = {
    /**
     * Image bytes
     */
    200: unknown;
};

export type GetProfileBannerData = {
    body?: never;
    path: {
        /**
         * Account id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/profiles/{account_id}/banner';
};

export type GetProfileBannerErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type GetProfileBannerError = GetProfileBannerErrors[keyof GetProfileBannerErrors];

export type GetProfileBannerResponses = {
    /**
     * Image bytes
     */
    200: unknown;
};

export type DeleteSpaceData = {
    body?: never;
    path: {
        /**
         * Space id
         */
        space_id: string;
    };
    query?: never;
    url: '/api/v1/spaces/{space_id}';
};

export type DeleteSpaceErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type DeleteSpaceError = DeleteSpaceErrors[keyof DeleteSpaceErrors];

export type DeleteSpaceResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteSpaceResponse = DeleteSpaceResponses[keyof DeleteSpaceResponses];

export type GetSpaceData = {
    body?: never;
    path: {
        /**
         * Space id
         */
        space_id: string;
    };
    query?: never;
    url: '/api/v1/spaces/{space_id}';
};

export type GetSpaceErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not a member
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type GetSpaceError = GetSpaceErrors[keyof GetSpaceErrors];

export type GetSpaceResponses = {
    /**
     * Space
     */
    200: SpaceResponse;
};

export type GetSpaceResponse = GetSpaceResponses[keyof GetSpaceResponses];

export type UpdateSpaceData = {
    body: UpdateSpaceRequest;
    path: {
        /**
         * Space id
         */
        space_id: string;
    };
    query?: never;
    url: '/api/v1/spaces/{space_id}';
};

export type UpdateSpaceErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not allowed
     */
    403: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type UpdateSpaceError = UpdateSpaceErrors[keyof UpdateSpaceErrors];

export type UpdateSpaceResponses = {
    /**
     * Updated space
     */
    200: SpaceResponse;
};

export type UpdateSpaceResponse = UpdateSpaceResponses[keyof UpdateSpaceResponses];
