// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Public account fields (never includes password hash).
 */
export type AccountResponse = {
    email?: string | null;
    id: string;
    is_bot: boolean;
    is_instance_admin: boolean;
};

/**
 * Authenticated session payload.
 */
export type AuthSessionResponse = {
    account: AccountResponse;
};

/**
 * Change email (requires current password; applied immediately until F117 adds confirmation mail).
 */
export type ChangeEmailRequest = {
    current_password: string;
    email: string;
};

/**
 * Change password (requires current password).
 */
export type ChangePasswordRequest = {
    current_password: string;
    new_password: string;
    /**
     * When true, delete all other sessions for this account (current session stays).
     */
    revoke_other_sessions?: boolean | null;
};

/**
 * JSON error envelope for `/api/v1` and unknown routes.
 */
export type ErrorBody = {
    code: string;
    details?: {
        [key: string]: unknown;
    } | null;
    message: string;
    request_id: string;
};

/**
 * Login with email and password.
 */
export type LoginRequest = {
    email: string;
    password: string;
};

/**
 * Build and version of this instance.
 */
export type MetaResponse = {
    name: string;
    version: string;
};

/**
 * Public profile fields.
 */
export type ProfileResponse = {
    account_id: string;
    avatar_url?: string | null;
    banner_url?: string | null;
    bio: string;
    display_name: string;
    has_avatar: boolean;
    has_banner: boolean;
};

/**
 * Register with email and password.
 */
export type RegisterRequest = {
    email: string;
    password: string;
};

/**
 * Patch display name and/or bio.
 */
export type UpdateProfileRequest = {
    bio?: string | null;
    display_name?: string | null;
};

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginErrors = {
    /**
     * Validation error
     */
    400: ErrorBody;
    /**
     * Invalid credentials
     */
    401: ErrorBody;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Logged in
     */
    200: AuthSessionResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutResponses = {
    /**
     * Logged out
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type GetMeErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * Current account
     */
    200: AuthSessionResponse;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type ChangeMyEmailData = {
    body: ChangeEmailRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me/email';
};

export type ChangeMyEmailErrors = {
    /**
     * Validation error
     */
    400: ErrorBody;
    /**
     * Wrong current password or not authenticated
     */
    401: ErrorBody;
    /**
     * Email taken
     */
    409: ErrorBody;
};

export type ChangeMyEmailError = ChangeMyEmailErrors[keyof ChangeMyEmailErrors];

export type ChangeMyEmailResponses = {
    /**
     * Email updated
     */
    200: AuthSessionResponse;
};

export type ChangeMyEmailResponse = ChangeMyEmailResponses[keyof ChangeMyEmailResponses];

export type ChangeMyPasswordData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me/password';
};

export type ChangeMyPasswordErrors = {
    /**
     * Validation error
     */
    400: ErrorBody;
    /**
     * Wrong current password or not authenticated
     */
    401: ErrorBody;
};

export type ChangeMyPasswordError = ChangeMyPasswordErrors[keyof ChangeMyPasswordErrors];

export type ChangeMyPasswordResponses = {
    /**
     * Password updated
     */
    204: void;
};

export type ChangeMyPasswordResponse = ChangeMyPasswordResponses[keyof ChangeMyPasswordResponses];

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterErrors = {
    /**
     * Validation error
     */
    400: ErrorBody;
    /**
     * Registration closed or CSRF
     */
    403: ErrorBody;
    /**
     * Email taken
     */
    409: ErrorBody;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Account created
     */
    201: AuthSessionResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type GetMyProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me/profile';
};

export type GetMyProfileErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
};

export type GetMyProfileError = GetMyProfileErrors[keyof GetMyProfileErrors];

export type GetMyProfileResponses = {
    /**
     * Own profile
     */
    200: ProfileResponse;
};

export type GetMyProfileResponse = GetMyProfileResponses[keyof GetMyProfileResponses];

export type UpdateMyProfileData = {
    body: UpdateProfileRequest;
    path?: never;
    query?: never;
    url: '/api/v1/me/profile';
};

export type UpdateMyProfileErrors = {
    /**
     * Validation error
     */
    400: ErrorBody;
    /**
     * Not authenticated
     */
    401: ErrorBody;
};

export type UpdateMyProfileError = UpdateMyProfileErrors[keyof UpdateMyProfileErrors];

export type UpdateMyProfileResponses = {
    /**
     * Updated profile
     */
    200: ProfileResponse;
};

export type UpdateMyProfileResponse = UpdateMyProfileResponses[keyof UpdateMyProfileResponses];

export type UploadMyAvatarData = {
    body?: unknown;
    path?: never;
    query?: never;
    url: '/api/v1/me/profile/avatar';
};

export type UploadMyAvatarErrors = {
    /**
     * Invalid or oversized image
     */
    400: ErrorBody;
    /**
     * Not authenticated
     */
    401: ErrorBody;
};

export type UploadMyAvatarError = UploadMyAvatarErrors[keyof UploadMyAvatarErrors];

export type UploadMyAvatarResponses = {
    /**
     * Updated profile
     */
    200: ProfileResponse;
};

export type UploadMyAvatarResponse = UploadMyAvatarResponses[keyof UploadMyAvatarResponses];

export type UploadMyBannerData = {
    body?: unknown;
    path?: never;
    query?: never;
    url: '/api/v1/me/profile/banner';
};

export type UploadMyBannerErrors = {
    /**
     * Invalid or oversized image
     */
    400: ErrorBody;
    /**
     * Not authenticated
     */
    401: ErrorBody;
};

export type UploadMyBannerError = UploadMyBannerErrors[keyof UploadMyBannerErrors];

export type UploadMyBannerResponses = {
    /**
     * Updated profile
     */
    200: ProfileResponse;
};

export type UploadMyBannerResponse = UploadMyBannerResponses[keyof UploadMyBannerResponses];

export type GetMetaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/meta';
};

export type GetMetaResponses = {
    /**
     * Instance name and version
     */
    200: MetaResponse;
};

export type GetMetaResponse = GetMetaResponses[keyof GetMetaResponses];

export type GetProfileData = {
    body?: never;
    path: {
        /**
         * Account id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/profiles/{account_id}';
};

export type GetProfileErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type GetProfileError = GetProfileErrors[keyof GetProfileErrors];

export type GetProfileResponses = {
    /**
     * Profile
     */
    200: ProfileResponse;
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type GetProfileAvatarData = {
    body?: never;
    path: {
        /**
         * Account id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/profiles/{account_id}/avatar';
};

export type GetProfileAvatarErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type GetProfileAvatarError = GetProfileAvatarErrors[keyof GetProfileAvatarErrors];

export type GetProfileAvatarResponses = {
    /**
     * Image bytes
     */
    200: unknown;
};

export type GetProfileBannerData = {
    body?: never;
    path: {
        /**
         * Account id
         */
        account_id: string;
    };
    query?: never;
    url: '/api/v1/profiles/{account_id}/banner';
};

export type GetProfileBannerErrors = {
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Not found
     */
    404: ErrorBody;
};

export type GetProfileBannerError = GetProfileBannerErrors[keyof GetProfileBannerErrors];

export type GetProfileBannerResponses = {
    /**
     * Image bytes
     */
    200: unknown;
};
