import {
  Ban,
  Bell,
  BellOff,
  Check,
  CheckCheck,
  ChevronsUp,
  Clock,
  Copy,
  FolderPlus,
  GitBranch,
  Link2,
  LogOut,
  type LucideIcon,
  Mail,
  MessageSquare,
  Pencil,
  Phone,
  Pin,
  Plus,
  Reply,
  Settings,
  Shield,
  Smile,
  Trash2,
  User,
  UserPlus,
} from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
  settings: Settings,
  'user-plus': UserPlus,
  plus: Plus,
  'folder-plus': FolderPlus,
  bell: Bell,
  'bell-off': BellOff,
  shield: Shield,
  edit: Pencil,
  'log-out': LogOut,
  check: Check,
  'check-check': CheckCheck,
  'chevrons-up': ChevronsUp,
  link: Link2,
  copy: Copy,
  trash: Trash2,
  smile: Smile,
  reply: Reply,
  'git-branch': GitBranch,
  pin: Pin,
  mail: Mail,
  message: MessageSquare,
  user: User,
  phone: Phone,
  clock: Clock,
  ban: Ban,
};
