name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: |
        cd client
        npm install
        
    - name: Build Desktop App
      run: |
        cd client
        npm run electron:build
      env:
        VUE_APP_API_URL: ${{ secrets.VUE_APP_API_URL }}
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: desktop-${{ matrix.os }}
        path: client/dist_electron/

  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
        
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
        
    - name: Install Dependencies
      run: |
        cd client
        npm install
        
    - name: Build Android App
      run: |
        cd client
        npm run capacitor:sync
        npm run capacitor:build android
      env:
        VUE_APP_API_URL: ${{ secrets.VUE_APP_API_URL }}
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: android-app
        path: client/android/app/build/outputs/ 